---
title: FLAIR
author: ''
date: '2020-04-09'
slug: flair
categories: []
tags:
  - ecology
subtitle: ''
summary: ''
authors: [rob]
lastmod: '2020-04-09T19:50:20+02:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Rob Skelton holds one of the *Future Leaders – African Independent Research (FLAIR)* Fellowships for talented African early career researchers who have the potential to become leaders in their field. These fellowships provide the opportunity to build an independent research career in a sub-Saharan African institution and to undertake cutting-edge scientific research that will address global challenges facing developing countries.

Royal Society website:
https://royalsociety.org/grants-schemes-awards/grants/flair/

Rob's project aims to produce robust mechanistic frameworks of plant response to the environment based on quantitative physiology. Sub-Saharahan Africa is one of the regions most vulnerable to drought and incremental warming. Climate change threatens water availability and important sectors that rely on natural ecosystems, such as forestry and tourism. This project aims to reduce uncertainty surrounding the capacity of natural ecosystems to withstand climate change by developing new fundamental insights that improve predictions of the ecological impacts of drought. One important expected outcome is a quantitative assessment to show how drought-induced changes to plant functionality in canopies affect long-term plant performance and viability – reducing uncertainty over the capacity of natural ecosystems to cope with water stress, and enabling more accurate and reliable predictions of plant health and productivity. The potential scientific, economic, and ecological benefits for South African communities are considerable. The development of innovative technologies to monitor plant health – including miniature external sapflow gauges – may well lead to new commercial products. This project is perfectly aligned with South Africa's research priorities in areas of long-term environmental change, for enduring scientific and societal benefit. 

