---
# Display name
title: Cederberg

# Username (this should match the folder name)
authors:
- cederberg

# Is this the primary user of the site?
superuser: false

# Role/position
role: 

# Organizations/Affiliations
organizations:
- name: South African Environmental Observation Network
  url: "www.saeon.ac.za"

# Short bio (displayed in user profile at end of posts)
bio: On the dry edge of the Fynbos Biome, the Cederberg offers the opportunity to explore the implications of a drier future for the biome.

research:


data: 

education outreach:
  courses:
  - course: stuff
    institution: stuff
    year: 2019


# Social/Academic Networking
# For available icons, see: https://sourcethemes.com/academic/docs/page-builder/#icons
#   For an email link, use "fas" icon pack, "envelope" icon, and a link in the
#   form "mailto:your-email@example.com" or "#contact" for contact widget.
# social:
# - icon: envelope
#   icon_pack: fas
#   link: "mailto:elvirena@saeon.ac.za"  # For a direct email link, use "mailto:test@example.org".
# - icon: twitter
#   icon_pack: fab
#   link: https://twitter.com/saeonews
# - icon: google-scholar
#   icon_pack: ai
#   link: https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=SAEON&before_author=Kwbp_-MBAAAJ&astart=0
#- icon: github
#  icon_pack: fab
#  link: https://github.com/saeon
# Link to a PDF of your resume/CV from the About widget.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# - icon: cv
#   icon_pack: ai
#   link: files/cv.pdf

# Enter email to display Gravatar (if Gravatar enabled in Config)
email: ""

# Organizational groups that you belong to (for People widget)
#   Set this to `[]` or comment out if you are not using People widget.
user_groups:
- Satellite study sites
---

On the dry edge of the Fynbos Biome, the Cederberg offers the opportunity to explore the implications of a drier future for the biome. 

SAEON's research in the Cederberg is predominantly ecological, although we do maintain high altitude weather observations at two tipping bucket rain gauges and an automatic weather station. You can view [real time data from the weather station here](http://lognet.saeon.ac.za:8088/EngCed/index.html#). The blue dots in the map below indicate our weather sites. Hover over each dot for details of the variables being collected.

```{r, echo=FALSE, warning=FALSE, message=FALSE}

#library(rgdal)
#library(sp)
#library(rgeos)
library(leaflet)
library(htmltools)

name = c("Sneeukop hut rain gauge <br/> (Hourly Rainfall and Temperature)",	"Engelsmanskloof weather station <br/> (Hourly Rainfall, Temperature, RH, Wind, Solar Rad)", "Sneeuberg rain gauge <br/> (Hourly Rainfall and Temperature)")

out <- data.frame(lat = c(-32.34862845,	-32.35355187,	-32.48524612), lon = c(19.17024213, 19.15030551, 19.16132639))

#offering <- c("Hourly Rainfall and Temperature", "Hourly Rainfall, Temperature, RH, Wind, Solar Rad", 	"Hourly Rainfall and Temperature")

###Plot the map
leaflet(data = out) %>%
  addTiles(group = "Default") %>%  # Add default OpenStreetMap map tiles
# addProviderTiles(provider = "Esri.WorldImagery", group = "Satellite") %>%
# addProviderTiles(provider = "Esri.WorldTopoMap", group = "Topo") %>%
  addCircleMarkers(label = 
                  lapply(name, HTML), 
                  radius = 3) #%>%
#   addLayersControl(
#    baseGroups = c("Default", "Satellite", "Topo"),
#    options = layersControlOptions(collapsed = FALSE)) %>%
#  hideGroup(c("Default", "Satellite"))

```

<br>

Our published ecological research in the Cederberg includes a [paleoecological study of hyrax middens](/publication/valsecchi-2013-vz/) and [methods for monitoring the charismatic Clanwilliam cedar](/publication/slingsby-2019-jy/). We have several other projects in the works, including relocating Hugh Taylor's vegetation survey plots from the 1980s, which we hope to resurvey.
