---
# Display name
title: Jonkershoek

# Username (this should match the folder name)
authors:
- jonkershoek

# Is this the primary user of the site?
superuser: false

# Role/position
role: 

# Organizations/Affiliations
organizations:
- name: South African Environmental Observation Network
  url: "www.saeon.ac.za"

# Short bio (displayed in user profile at end of posts)
bio: One of the longest running multiple catchment experiments in the world.

research:


data: 

education outreach:
  courses:
  - course: stuff
    institution: stuff
    year: 2019


# Social/Academic Networking
# For available icons, see: https://sourcethemes.com/academic/docs/page-builder/#icons
#   For an email link, use "fas" icon pack, "envelope" icon, and a link in the
#   form "mailto:your-email@example.com" or "#contact" for contact widget.
# social:
# - icon: envelope
#   icon_pack: fas
#   link: "mailto:elvirena@saeon.ac.za"  # For a direct email link, use "mailto:test@example.org".
# - icon: twitter
#   icon_pack: fab
#   link: https://twitter.com/saeonews
# - icon: google-scholar
#   icon_pack: ai
#   link: https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=SAEON&before_author=Kwbp_-MBAAAJ&astart=0
#- icon: github
#  icon_pack: fab
#  link: https://github.com/saeon
# Link to a PDF of your resume/CV from the About widget.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# - icon: cv
#   icon_pack: ai
#   link: files/cv.pdf

# Enter email to display Gravatar (if Gravatar enabled in Config)
email: ""

# Organizational groups that you belong to (for People widget)
#   Set this to `[]` or comment out if you are not using People widget.
user_groups:
- Core study sites

---
## Overview

SAEON have focussed on establishing Jonkershoek as an open, long term, cross-disciplinary platform with comprehensive equipment arrays for observing climate, water, carbon and biodiversity, where the longevity and quality of the data are assured and readily accessible. We have also focused on capturing and making available the historical archives of hydrological and ecological datasets. Some of the long term rainfall and stream flow data are presented in our [**Catchment Monitor**](/dashboards/catchment/) and you can view real time data from our high altitude weather station [**here**](http://lognet.saeon.ac.za:8088/Dwarsberg/index.html). We illustrate the current and historical observation sites in the following map and describe some of the history of the site and ecological data below. We have almost completed a preliminary archive of the ecological datasets and hope to provide more descriptive information and details on how to access them soon.

<br>

## Map of field instruments

The blue dots in the map below indicate our instrumented sites. Hover over each dot for details of the variables being collected. If you are interested in accessing any of these data please [**contact us**](/#contact). 

```{r, echo=FALSE, warning=FALSE, message=FALSE}

#library(rgdal)
#library(sp)
#library(rgeos)
library(readxl)
library(leaflet)
library(htmltools)

dat <- read_xlsx("/home/jasper/Dropbox/SAEON/Management/Website/SAEON_field instrument list.xlsx", sheet = 1)

mdat <- dat[which(dat$Site == "Jonkershoek" & dat$Owner == "SAEON"  & dat$Class %in% c("Meteorological", "Micro meteorological")),]
mname = paste0(mdat$`Station name`, " <br/> ", "(", mdat$Variables, ")")
mdat <- data.frame(lat = mdat$Latitude, lon = mdat$Longitude)

hdat <- dat[which(dat$Site == "Jonkershoek" & dat$Owner == "SAEON"  & dat$Class == "Hydrological"),]
hname = paste0(hdat$`Station name`, " <br/> ", "(", hdat$Variables, ")")
hdat <- data.frame(lat = hdat$Latitude, lon = hdat$Longitude)


#offering <- c("Hourly Rainfall and Temperature", "Hourly Rainfall, Temperature, RH, Wind, Solar Rad", 	"Hourly Rainfall and Temperature")

###Plot the map
leaflet() %>%
  addTiles(group = "Default") %>%  # Add default OpenStreetMap map tiles
# addProviderTiles(provider = "Esri.WorldImagery", group = "Satellite") %>%
# addProviderTiles(provider = "Esri.WorldTopoMap", group = "Topo") %>%
  addCircleMarkers(data = mdat,
                   label = 
                  lapply(mname, HTML), 
                  group = "Meteorological",
                  radius = 3) %>%
  
  addCircleMarkers(data = hdat,
                   label = 
                  lapply(hname, HTML), 
                  group = "Hydrological",
                  radius = 3, 
                  color = "red") %>%
   addLayersControl(overlayGroups = 
                      c("Meteorological", "Hydrological"),
                  #  baseGroups = 
                  #    c("Default", "Satellite"),
    options = layersControlOptions(collapsed = FALSE)) #%>%
#  hideGroup(c("Default", "Satellite"))

```

<br>

## History

The Jonkershoek multiple catchment experiment has been running since the 1930s and is the oldest in Africa and one of the longest running in the world. The initial aim was to determine how forestry activities in state plantations affect climate, water conservation and erosion, and the ambit of the Jonkershoek Forestry Research Centre (JFRC) was later expanded to include studies of fynbos ecology, fire and alien species.

The initial experiment consists of six neighbouring catchments previously supporting natural fynbos vegetation, five of which were successively afforested with *Pinus* spp plantations every 8 years from 1940 to 1980 and one kept as the fynbos control. The treatment catchments have seen subsequent plantation rotations since 1980. All catchments were equipped with gauging weirs and multiple temperature and rain gauges.

The 1930s to the early 1990s saw the accumulation of the longest continuous records for stream flow in the Southern hemisphere, which revealed that afforestation results in dramatic reduction in stream flow. It also saw the gathering of a large amount of data dealing with fire experiments, detailed vegetation plot surveys, rare plant surveys and ecological studies, and the development of management plans for catchments around the Western Cape.

The JFRC was disbanded and absorbed by the CSIR and other bodies in the early 1990s. Data collection from the catchment experiment was maintained by volunteers on an ad hoc basis until SAEON inherited the catchment experiment in 2009. We have since refurbished the instrumentation to continue their long term observations to address global change related questions. 



