---
# Display name
title: Meteorology

# Username (this should match the folder name)
authors:
- meteorology

# Is this the primary user of the site?
superuser: false

# Role/position
role: 

# Organizations/Affiliations
organizations:
- name: South African Environmental Observation Network
  url: http://www.saeon.ac.za

# Short bio (displayed in user profile at end of posts)
# bio: One of the most biodiverse and imperilled landscapes in the world.
# 
# research:
# 
# data: Lots
# 
# education outreach:
#   courses:
#   - course: stuff
#     institution: stuff
#     year: 2019


# Social/Academic Networking
# For available icons, see: https://sourcethemes.com/academic/docs/page-builder/#icons
#   For an email link, use "fas" icon pack, "envelope" icon, and a link in the
#   form "mailto:your-email@example.com" or "#contact" for contact widget.
# social:
# - icon: envelope
#   icon_pack: fas
#   link: "mailto:elvirena@saeon.ac.za"  # For a direct email link, use "mailto:test@example.org".
# - icon: twitter
#   icon_pack: fab
#   link: https://twitter.com/saeonews
# - icon: google-scholar
#   icon_pack: ai
#   link: https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=SAEON&before_author=Kwbp_-MBAAAJ&astart=0
#- icon: github
#  icon_pack: fab
#  link: https://github.com/saeon
# Link to a PDF of your resume/CV from the About widget.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# - icon: cv
#   icon_pack: ai
#   link: files/cv.pdf

# Enter email to display Gravatar (if Gravatar enabled in Config)
email: ""

# Organizational groups that you belong to (for People widget)
#   Set this to `[]` or comment out if you are not using People widget.
user_groups:
- Datasets
---

We maintain a number of automatic weather stations, tipping bucket rain gauges and temperature loggers at our main study sites (see map below). Three of our high altitude weather stations can be accessed online to view live weather data and the record over the past month. These include [Dwarsberg in Jonkershoek](http://lognet.saeon.ac.za:8088/Dwarsberg/index.html), [Constantiaberg Peak on the Cape Peninsula](http://lognet.saeon.ac.za:8088/Constantiaberg/index.html) and [Engelsmanskloof in the Cederberg](http://lognet.saeon.ac.za:8088/EngCed/index.html). A long term analysis of the Jonkershoek rainfall and streamflow can be viewed in our [Catchment Monitor](/dashboards/catchment/).

We hope to add links to the data in the near future, but in the mean time please [contact us](/#contact) if you're interested.

We are also running a network of temperature and humidity loggers throughout the Cape Peninsula and started collecting Eddy Covariance data in Jonkershoek in 2019. These data are not yet readily available through our datasystems as we are still troubleshooting quality assurance and quality control protocols, but if you are interested you are welcome to [contact us](/#contact).

```{r, echo=FALSE, warning=FALSE, message=FALSE}

library(readxl)
library(leaflet)
library(htmltools)

dat <- read_xlsx("/home/jasper/Dropbox/SAEON/Management/Website/SAEON_field instrument list.xlsx", sheet = 1)

mdat <- dat[which(dat$Node == "Fynbos" & dat$Owner == "SAEON"  & dat$Class %in% c("Meteorological", "Micro meteorological")),]
mname = paste0(mdat$`Station name`, " <br/> ", "(", mdat$Variables, ")")
mdat <- data.frame(lat = mdat$Latitude, lon = mdat$Longitude)

# hdat <- dat[which(dat$Node == "Fynbos" & dat$Owner == "SAEON"  & dat$Class == "Hydrological"),]
# hname = paste0(hdat$`Station name`, " <br/> ", "(", hdat$Variables, ")")
# hdat <- data.frame(lat = hdat$Latitude, lon = hdat$Longitude)


#offering <- c("Hourly Rainfall and Temperature", "Hourly Rainfall, Temperature, RH, Wind, Solar Rad", 	"Hourly Rainfall and Temperature")

###Plot the map
leaflet() %>%
  addTiles(group = "Default") %>%  # Add default OpenStreetMap map tiles
# addProviderTiles(provider = "Esri.WorldImagery", group = "Satellite") %>%
# addProviderTiles(provider = "Esri.WorldTopoMap", group = "Topo") %>%
  addCircleMarkers(data = mdat,
                   label =
                  lapply(mname, HTML),
                  group = "Meteorological",
                  radius = 3) #%>%
  
  # addCircleMarkers(data = hdat,
  #                  label = 
  #                 lapply(hname, HTML), 
  #                 group = "Hydrological",
  #                 radius = 3) %>%
  # addLayersControl(
     #overlayGroups = 
      #                c("Meteorological", "Hydrological"),
  #                  baseGroups = 
  #                    c("Default", "Satellite"),
  #  options = layersControlOptions(collapsed = FALSE)) #%>%
#  hideGroup(c("Default", "Satellite"))

```

